/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Flights extends javax.swing.JFrame {
    Connection con;
      DefaultTableModel dtm;
    /**
     * Creates new form Flights
     */
    public Flights() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tf_flightCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_numSeats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_show = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_flight = new javax.swing.JTable();
        btn_back1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        tf_landing = new javax.swing.JTextField();
        tf_takeoff = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Flight");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_flightCode.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_flightCode.setForeground(new java.awt.Color(102, 102, 102));
        tf_flightCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_flightCodeActionPerformed(evt);
            }
        });
        jPanel3.add(tf_flightCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Flight Code");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 25));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 75, -1));

        tf_date.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_date.setForeground(new java.awt.Color(102, 102, 102));
        tf_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dateActionPerformed(evt);
            }
        });
        jPanel3.add(tf_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 120, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("TakeOff");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, -1));

        tf_numSeats.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_numSeats.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_numSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 150, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Number of Seats");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 69, -1, -1));

        btn_show.setBackground(new java.awt.Color(204, 204, 204));
        btn_show.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_show.setText("Show");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        jPanel3.add(btn_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 120, 25));

        btn_edit.setBackground(new java.awt.Color(204, 204, 204));
        btn_edit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel3.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 26));

        btn_save.setBackground(new java.awt.Color(204, 204, 204));
        btn_save.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, 26));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Manage Flight");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 11, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Flight List");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        t_flight.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        t_flight.setForeground(new java.awt.Color(102, 102, 102));
        t_flight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fligth Code", "Takeoff", "Landing ", "Date of Takeoff", "Number Of Seats"
            }
        ));
        t_flight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_flightMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_flight);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 780, 200));

        btn_back1.setBackground(new java.awt.Color(255, 255, 255));
        btn_back1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_back1.setForeground(new java.awt.Color(255, 255, 255));
        btn_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return (1).png"))); // NOI18N
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Takeoff Date");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 69, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Landing");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 80, -1));

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 120, 25));

        btn_search.setBackground(new java.awt.Color(204, 204, 204));
        btn_search.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel3.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 25));
        jPanel3.add(tf_landing, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 110, -1));
        jPanel3.add(tf_takeoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/src/images/flightttttt.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateActionPerformed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement stat =con.prepareStatement("SELECT * FROM airline.flights;");
            ResultSet rs =stat.executeQuery();
            dtm =new DefaultTableModel();
            dtm.addColumn("Flight Code");
            dtm.addColumn("TakeOff");
            dtm.addColumn("Landing");
            dtm.addColumn("Date Of TakeOff");
            dtm.addColumn("Seats");




            while (rs.next()) {                
                dtm.addRow(new Object [] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5)});
            }
                  t_flight.setModel(dtm);

        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement stmt =con.prepareStatement("INSERT INTO `airline`.`flights` (`fl_id`, `fl_takeoff`, `fl_landing`, `fl_date`, `fl_seats`) VALUES (?, ?, ?, ?,?);");
            
            String  flightCode = tf_flightCode.getText();
            String  takeOff = tf_takeoff.getText();
            String  landing = tf_landing.getText();
            String  takeOffDate = tf_date.getText();
            int numSeats = Integer.parseInt(tf_numSeats.getText()) ;
            
            stmt.setString(1, flightCode);
            stmt.setString(2, takeOff);
            stmt.setString(3, landing);
            stmt.setString(4, takeOffDate);
            stmt.setInt(5, numSeats);

            stmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Save Success");
            
            tf_flightCode.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
            tf_date.setText("");
            tf_numSeats.setText("");
            
             btn_saveActionPerformed(evt);
         } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
          new mainWindow().setVisible(true);
            //this.setVisible(false);
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("delete from flights where fl_id=?");
            String fl_id = tf_flightCode.getText();
            stmt.setString(1, fl_id);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete Success");
            
            btn_showActionPerformed(evt);
             tf_flightCode.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
            tf_date.setText("");
            tf_numSeats.setText("");
            


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from  flights where fl_takeoff = ? and fl_landing = ?");
            String takeOff = tf_takeoff.getText();
            String landing = tf_landing.getText();
            stmt.setString(1, takeOff);
            stmt.setString(2, landing);
            ResultSet set = stmt.executeQuery(); 
            if (set.next()) {
                tf_flightCode.setText(set.getString("fl_id")); 
                tf_date.setText(set.getString("fl_date")); 
                tf_numSeats.setText(set.getString("fl_seats")); 
                
            } else {
                JOptionPane.showMessageDialog(this, "Not Found"); //if the id not in the table 
            }

        } catch (SQLException ex) {
            System.out.println(ex); 
        }
//      String fl_id = tf_flightCode.getText();
//        
//        try {
//            // TODO add your handling code here:
//
//            PreparedStatement stat=con.prepareStatement("SELECT * FROM airline.flights where fl_id='"+fl_id+"'");
//            //String fl_id = tf_flightCode.getText();
//            
//            stat.setString(1, fl_id);
//            ResultSet rs =stat.executeQuery();
//            if(rs.next())
//            {
//                tf_takeoff.setText(rs.getString(rs.getString(2)));
//                tf_landing.setText(rs.getString(rs.getString(3)));
//                tf_date.setText(rs.getString(rs.getString(4)));
//                tf_numSeats.setText(rs.getString(rs.getString(5)));
//                tf_flightCode.setEditable(false);
//                
//            }else{
//                JOptionPane.showMessageDialog(this, "Flight Doesn't Exist");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            // TODO add your handling code here:
            
            PreparedStatement stmt = con.prepareStatement("UPDATE `airline`.`flights` SET  `fl_takeoff` = ?, `fl_landing` = ?, `fl_date` = ?, `fl_seats` = ? WHERE `fl_id` = ?");
            
           // String flight_code = tf_flightCode.getText();
            String fl_takeoff = tf_takeoff.getText();
            String fl_landing = tf_landing.getText();
            String fl_date = tf_date.getText();
            String fl_seats = tf_numSeats.getText();
            String fl_id = tf_flightCode.getText();
            
            
            stmt.setString(1, fl_takeoff);
            stmt.setString(2, fl_landing);
            stmt.setString(3, fl_date);
            stmt.setString(4, fl_seats);
            stmt.setString(5,fl_id) ;
            

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Edit Success");
            btn_showActionPerformed(evt);
            
            tf_flightCode.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
            tf_date.setText("");
            tf_numSeats.setText("");
 
        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
           

        
    }//GEN-LAST:event_btn_editActionPerformed

    private void tf_flightCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_flightCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_flightCodeActionPerformed

    private void t_flightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_flightMouseClicked
        // TODO add your handling code here:
        int row_num = t_flight.getSelectedRow();
        String fl_id = t_flight.getValueAt(row_num, 0).toString();
        String fl_takeoff = t_flight.getValueAt(row_num, 1).toString();
        String fl_landing= t_flight.getValueAt(row_num, 2).toString();
        String fl_date = t_flight.getValueAt(row_num, 3).toString();
        String fl_seats = t_flight.getValueAt(row_num, 4).toString();
     

        tf_flightCode.setText(fl_id);
        tf_takeoff.setText(fl_takeoff);
        tf_landing.setText(fl_landing);
        tf_date.setText(fl_date);
        tf_numSeats.setText(fl_seats);
        
    }//GEN-LAST:event_t_flightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_flight;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_flightCode;
    private javax.swing.JTextField tf_landing;
    private javax.swing.JTextField tf_numSeats;
    private javax.swing.JTextField tf_takeoff;
    // End of variables declaration//GEN-END:variables
}
