/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author hp
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_flight = new javax.swing.JButton();
        btn_passenger = new javax.swing.JButton();
        btn_ticket = new javax.swing.JButton();
        btn_infoPage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_flight.setBackground(new java.awt.Color(204, 204, 204));
        btn_flight.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_flight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/flight.png"))); // NOI18N
        btn_flight.setText("Flights");
        btn_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flightActionPerformed(evt);
            }
        });
        jPanel1.add(btn_flight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));

        btn_passenger.setBackground(new java.awt.Color(204, 204, 204));
        btn_passenger.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_passenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/immigration (1).png"))); // NOI18N
        btn_passenger.setText("Passengers");
        btn_passenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passengerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_passenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 180, -1));

        btn_ticket.setBackground(new java.awt.Color(204, 204, 204));
        btn_ticket.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/tickets.png"))); // NOI18N
        btn_ticket.setText("Tickets");
        btn_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ticketActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        btn_infoPage.setBackground(new java.awt.Color(204, 204, 204));
        btn_infoPage.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_infoPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/file.png"))); // NOI18N
        btn_infoPage.setText("Informations");
        btn_infoPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoPageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_infoPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 180, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/src/images/home.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flightActionPerformed
        // TODO add your handling code here:
         new Flights().setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btn_flightActionPerformed

    private void btn_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ticketActionPerformed
        // TODO add your handling code here:
         new Tickets_booking().setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btn_ticketActionPerformed

    private void btn_passengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passengerActionPerformed
        // TODO add your handling code here:
            new Passengers().setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btn_passengerActionPerformed

    private void btn_infoPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoPageActionPerformed
        // TODO add your handling code here:
        new info().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btn_infoPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_flight;
    private javax.swing.JButton btn_infoPage;
    private javax.swing.JButton btn_passenger;
    private javax.swing.JButton btn_ticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
