/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Passengers extends javax.swing.JFrame {

     Connection con;
      DefaultTableModel dtm;
    /**
     * Creates new form Passengers
     */
    public Passengers() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_passportNumber = new javax.swing.JTextField();
        tf_Fname = new javax.swing.JTextField();
        tf_Lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nationality = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_book = new javax.swing.JButton();
        btn_book1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_book2 = new javax.swing.JButton();
        btn_book3 = new javax.swing.JButton();
        tf_gender = new javax.swing.JTextField();
        t_passengers = new javax.swing.JScrollPane();
        t_passengerss = new javax.swing.JTable();
        la = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Passengers");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Passport Number");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Passengers");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" First Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        tf_passportNumber.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_passportNumber.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_passportNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));

        tf_Fname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_Fname.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));

        tf_Lname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_Lname.setForeground(new java.awt.Color(102, 102, 102));
        tf_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LnameActionPerformed(evt);
            }
        });
        jPanel3.add(tf_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Last Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        tf_phone.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_phone.setForeground(new java.awt.Color(102, 102, 102));
        tf_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phoneActionPerformed(evt);
            }
        });
        jPanel3.add(tf_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 100, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nationality");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        tf_nationality.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_nationality.setForeground(new java.awt.Color(102, 102, 102));
        tf_nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nationalityActionPerformed(evt);
            }
        });
        jPanel3.add(tf_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, -1));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeicone.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel3.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        btn_book.setBackground(new java.awt.Color(204, 204, 204));
        btn_book.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_book.setText("Edit");
        btn_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        btn_book1.setBackground(new java.awt.Color(204, 204, 204));
        btn_book1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_book1.setText("Search");
        btn_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Passengers List");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        btn_book2.setBackground(new java.awt.Color(204, 204, 204));
        btn_book2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_book2.setText("Show");
        btn_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        btn_book3.setBackground(new java.awt.Color(204, 204, 204));
        btn_book3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_book3.setText("Save");
        btn_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));
        jPanel3.add(tf_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 70, -1));

        t_passengerss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_passengerss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_passengerssMouseClicked(evt);
            }
        });
        t_passengers.setViewportView(t_passengerss);

        jPanel3.add(t_passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 810, 180));

        la.setBackground(new java.awt.Color(204, 204, 204));
        la.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/src/images/passengers.jpg"))); // NOI18N
        jPanel3.add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 520));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phoneActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mainWindow().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("delete from `airline`.`passengers` where passport_id=?");
            String passport_id = tf_passportNumber.getText();
            stmt.setString(1, passport_id);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete Success");
            
            btn_book2ActionPerformed(evt);
            tf_passportNumber.setText("");
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_phone.setText("");
            tf_nationality.setText("");
            


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book1ActionPerformed
        // TODO add your handling code here:
          try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from  passengers where passport_id = ?");
            String passport_id = tf_passportNumber.getText();
          
            stmt.setString(1, passport_id);
            java.sql.ResultSet set = stmt.executeQuery(); 
            if (set.next()) {
                tf_Fname.setText(set.getString("pass_fname")); 
                tf_Lname.setText(set.getString("pass_lname"));
                tf_gender.setText(set.getString("pass_gender"));
                tf_phone.setText(set.getString("pass_phone")); 
                tf_nationality.setText(set.getString("pass_nationality")); 
                
            } else {
                JOptionPane.showMessageDialog(this, "Not Found"); //if the id not in the table 
            }

        } catch (SQLException ex) {
            System.out.println(ex); 
        }
    }//GEN-LAST:event_btn_book1ActionPerformed

    private void tf_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LnameActionPerformed

    private void tf_nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nationalityActionPerformed

    private void btn_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book2ActionPerformed
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from passengers");
             java.sql.ResultSet set =   stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("passport_id");
            dm.addColumn("pass_fname");
            dm.addColumn("pass_lname");
            dm.addColumn("pass_gender");
            dm.addColumn("pass_phone");
            dm.addColumn("pass_nationality");
            

            while (set.next()) {
               dm.addRow(new Object [] {set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)});
            }

             
            t_passengerss.setModel(dm);

        } catch (SQLException ex) {
            System.out.println(ex);}
    }//GEN-LAST:event_btn_book2ActionPerformed

    private void btn_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book3ActionPerformed
        // TODO add your handling code here
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into passengers(passport_id , pass_fname  , pass_lname  , pass_gender  ,pass_phone , pass_nationality ) values(?,?,?,?,?,?)");
            String passport_id = tf_passportNumber.getText();
            String pass_fname = tf_Fname.getText();
            String pass_lname = tf_Lname.getText();
            String pass_gender = tf_gender.getText();
            String pass_phone = tf_phone.getText();
            String pass_nationality= tf_nationality.getText();
            
            stmt.setString(1, passport_id);
            stmt.setString(2, pass_fname);
            stmt.setString(3, pass_lname);
            stmt.setString(4, pass_gender);
            stmt.setString(5, pass_phone);
            stmt.setString(6, pass_nationality);
           

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Save Success");
            tf_passportNumber.setText("");
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_phone.setText("");
            tf_nationality.setText("");
            

          // btn_book3ActionPerformed(evt);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_book3ActionPerformed

    private void t_passengerssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_passengerssMouseClicked
        // TODO add your handling code here:
         int row_num = t_passengerss.getSelectedRow();
        String passport_id  = t_passengerss.getValueAt(row_num, 0).toString();
        String pass_fname = t_passengerss.getValueAt(row_num, 1).toString();
        String pass_lname= t_passengerss.getValueAt(row_num, 2).toString();
        String pass_gender = t_passengerss.getValueAt(row_num, 3).toString();
        String pass_phone = t_passengerss.getValueAt(row_num, 4).toString();
         String pass_nationality = t_passengerss.getValueAt(row_num, 5).toString();
         

        tf_passportNumber.setText(passport_id);
        tf_Fname.setText(pass_fname);
        tf_Lname.setText(pass_lname);
        tf_gender.setText(pass_gender);
        tf_phone.setText(pass_phone);
        tf_nationality.setText(pass_nationality);
        
    }//GEN-LAST:event_t_passengerssMouseClicked

    private void btn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            
            PreparedStatement stmt = con.prepareStatement("UPDATE `airline`.`passengers` SET  `pass_fname` = ?, `pass_lname` = ?, `pass_gender` = ?,`pass_phone` = ?,`pass_nationality` = ? WHERE `passport_id` = ?");
            
           // String flight_code = tf_flightCode.getText();
            String pass_fname = tf_Fname.getText();
            String pass_lname = tf_Lname.getText();
            String pass_gender = tf_gender.getText();
            String pass_phone = tf_phone.getText();
            String pass_nationality = tf_nationality.getText();
            String passport_id = tf_passportNumber.getText();
            
            
            stmt.setString(1, pass_fname);
            stmt.setString(2, pass_lname);
            stmt.setString(3, pass_gender);
            stmt.setString(4, pass_phone);
            stmt.setString(5,pass_nationality) ;
             stmt.setString(6,passport_id) ;
            

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Edit Success");
            btn_book2ActionPerformed(evt);
            
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_phone.setText("");
            tf_nationality.setText("");
            tf_passportNumber.setText("");
 
        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btn_bookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_book;
    private javax.swing.JButton btn_book1;
    private javax.swing.JButton btn_book2;
    private javax.swing.JButton btn_book3;
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel la;
    private javax.swing.JScrollPane t_passengers;
    private javax.swing.JTable t_passengerss;
    private javax.swing.JTextField tf_Fname;
    private javax.swing.JTextField tf_Lname;
    private javax.swing.JTextField tf_gender;
    private javax.swing.JTextField tf_nationality;
    private javax.swing.JTextField tf_passportNumber;
    private javax.swing.JTextField tf_phone;
    // End of variables declaration//GEN-END:variables

    private static class con {

        public con() {
        }
    }

    private static class ResultSet {

        public ResultSet() {
        }

        private boolean next() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private String getString(int i) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}

