/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Tickets_booking extends javax.swing.JFrame {

    /**
     * Creates new form Tickets_booking
     */
    public Tickets_booking() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_Lname = new javax.swing.JTextField();
        tf_Fname = new javax.swing.JTextField();
        tf_passportNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_nationality = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_show = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_book1 = new javax.swing.JButton();
        btn_book2 = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        tf_flightcode = new javax.swing.JTextField();
        tf_gender = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_ticket = new javax.swing.JTable();
        search2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_takeoff = new javax.swing.JTextField();
        tf_landing = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tickets Booking");
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Passport Number");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText(" First Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Tickets Booking");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        tf_Lname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_Lname.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, -1));

        tf_Fname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_Fname.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, -1));

        tf_passportNumber.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_passportNumber.setForeground(new java.awt.Color(102, 102, 102));
        tf_passportNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passportNumberActionPerformed(evt);
            }
        });
        jPanel3.add(tf_passportNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Landing");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 110, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText(" Last Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Date");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        tf_date.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_date.setForeground(new java.awt.Color(102, 102, 102));
        tf_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dateActionPerformed(evt);
            }
        });
        jPanel3.add(tf_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Nationality");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        tf_nationality.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_nationality.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(tf_nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 100, -1));

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-on-investment (1).png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel3.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_reset.setBackground(new java.awt.Color(255, 255, 255));
        btn_reset.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_reset.setText("Delete");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 100, -1));

        btn_show.setBackground(new java.awt.Color(204, 204, 204));
        btn_show.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_show.setText("Show");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        jPanel3.add(btn_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 100, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText(" Bookings");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        btn_book1.setBackground(new java.awt.Color(204, 204, 204));
        btn_book1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_book1.setText("Update");
        btn_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 100, -1));

        btn_book2.setBackground(new java.awt.Color(204, 204, 204));
        btn_book2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_book2.setText("Search");
        btn_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_book2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 150, -1));

        btn_save.setBackground(new java.awt.Color(204, 204, 204));
        btn_save.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_save.setText("Book");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 100, -1));

        tf_flightcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_flightcodeActionPerformed(evt);
            }
        });
        jPanel3.add(tf_flightcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, -1));

        tf_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_genderActionPerformed(evt);
            }
        });
        jPanel3.add(tf_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, -1));

        t_ticket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_ticketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_ticket);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 560, 260));

        search2.setBackground(new java.awt.Color(204, 204, 204));
        search2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        search2.setText("Search");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });
        jPanel3.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 150, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Flight Code");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("TakeOff");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 110, -1));
        jPanel3.add(tf_takeoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 110, -1));
        jPanel3.add(tf_landing, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 110, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/src/images/ticket22.jpg"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 531));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new mainWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("delete from `airline`.`tickets` where passport_id=?");
            String passport_id = tf_passportNumber.getText();
            stmt.setString(1, passport_id);
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete Success");
            
            btn_showActionPerformed(evt);
            tf_passportNumber.setText("");
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_nationality.setText("");
            tf_date.setText("");
            tf_flightcode.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
            


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stat =con.prepareStatement("select *from tickets ");
            ResultSet rs =stat.executeQuery();
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Passport Nnmber");
            dtm.addColumn("First Name");
            dtm.addColumn("Last Name");
            dtm.addColumn(" Gender ");
            dtm.addColumn("Nationality");
            dtm.addColumn("Flight Code");
            dtm.addColumn("Date");
            dtm.addColumn("TakeOff");
            dtm.addColumn("Landing");
 
            while (rs.next()) {                
                dtm.addRow(new Object [] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            }
                  t_ticket.setModel(dtm);

        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book1ActionPerformed
        
         try {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root"); 
            PreparedStatement stmt = con.prepareStatement("UPDATE `airline`.`tickets` SET   `pass_fname` = ?, `pass_lname` = ?, `pass_gender` = ?, `pass_nationality` = ?, `fl_id` = ? , `fl_date` = ?,`fl_takeoff` = ?,`fl_landing` = ? WHERE `passport_id` = ?");
          

            String pass_fname = tf_Fname.getText();
            String pass_lname = tf_Lname.getText();
            String pass_gender = tf_gender.getText();
            String pass_nationality = tf_nationality.getText();
            String fl_id = tf_flightcode.getText();
            String fl_date = tf_date.getText();
            String passport_id = tf_passportNumber.getText();
            String fl_takeoff = tf_takeoff.getText();
            String fl_landing = tf_landing.getText();
              
            stmt.setString(1, pass_fname);
            stmt.setString(2, pass_lname);
            stmt.setString(3, pass_gender);
            stmt.setString(4, pass_nationality);
            stmt.setString(5,fl_id) ;
            stmt.setString(6,fl_date) ;
            stmt.setString(7,fl_takeoff) ;
            stmt.setString(8,fl_landing) ;
            stmt.setString(9,passport_id) ;

            stmt.executeUpdate();
            JOptionPane.showMessageDialog( this, "Edit Success" );
            btn_showActionPerformed(evt);
              
            tf_passportNumber.setText("");
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_nationality.setText("");
            tf_flightcode.setText("");
            tf_date.setText("");
            tf_passportNumber.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
 
        } catch (SQLException ex) {
            Logger.getLogger(Flights.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btn_book1ActionPerformed

    private void btn_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_book2ActionPerformed
        // TODO add your handling code here:
        try 
        {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from  passengers where passport_id = ?");
            String passport_id = tf_passportNumber.getText();
            stmt.setString( 1, passport_id );
            ResultSet set = stmt.executeQuery(); 
            if (set.next()) {
                tf_Fname.setText(set.getString("pass_fname")); 
                tf_Lname.setText(set.getString("pass_lname"));
                tf_gender.setText(set.getString("pass_gender"));
                tf_nationality.setText(set.getString("pass_nationality")); 
                
            } 
            else
            {
                JOptionPane.showMessageDialog(this, "Not Found"); //if the id not in the table 
            }

        } catch (SQLException ex) {
            System.out.println(ex); 
        }
    }//GEN-LAST:event_btn_book2ActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into tickets (passport_id , pass_fname , pass_lname , pass_gender , pass_nationality , fl_date , fl_id, fl_takeoff, fl_landing ) values(?,?,?,?,?,?,?,?,?)");
            String passport_id = tf_passportNumber.getText();
            String pass_fname = tf_Fname.getText();
            String pass_lname = tf_Lname.getText();
            String pass_gender = tf_gender.getText();
            String pass_nationality = tf_nationality.getText();
            String fl_date= tf_date.getText();
            String fl_id= tf_flightcode.getText();
            String fl_takeoff= tf_takeoff.getText();
            String fl_landing= tf_landing.getText();
            
            stmt.setString(1, passport_id);
            stmt.setString(2, pass_fname);
            stmt.setString(3, pass_lname);
            stmt.setString(4, pass_gender);
            stmt.setString(5, pass_nationality);
            stmt.setString(6, fl_date);
            stmt.setString(7, fl_id);
            stmt.setString(8, fl_takeoff);
            stmt.setString(9, fl_landing);
           

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Save Success");
            tf_passportNumber.setText("");
            tf_Fname.setText("");
            tf_Lname.setText("");
            tf_gender.setText("");
            tf_nationality.setText("");
            tf_date.setText("");
            tf_flightcode.setText("");
            tf_takeoff.setText("");
            tf_landing.setText("");
            btn_showActionPerformed(evt);
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tf_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_genderActionPerformed

    private void t_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_ticketMouseClicked
        // TODO add your handling code here:
        int row_num = t_ticket.getSelectedRow();
        String passport_id  = t_ticket.getValueAt(row_num, 0).toString();
        String pass_fname = t_ticket.getValueAt(row_num, 1).toString();
        String pass_lname= t_ticket.getValueAt(row_num, 2).toString();
        String pass_gender = t_ticket.getValueAt(row_num, 3).toString();
        String pass_nationalitypassengers = t_ticket.getValueAt(row_num, 4).toString();
        String fl_date  = t_ticket.getValueAt(row_num, 6).toString();
        String fl_id  = t_ticket.getValueAt(row_num, 5).toString();
        String fl_takeoff  = t_ticket.getValueAt(row_num, 7).toString();
        String fl_landing  = t_ticket.getValueAt(row_num, 8).toString();
         

        tf_passportNumber.setText(passport_id);
        tf_Fname.setText(pass_fname);
        tf_Lname.setText(pass_lname);
        tf_gender.setText(pass_gender);
        tf_nationality.setText(pass_nationalitypassengers);
        tf_date.setText(fl_date);
        tf_flightcode.setText(fl_id);
        tf_takeoff.setText(fl_takeoff);
        tf_landing.setText(fl_landing);
        
    }//GEN-LAST:event_t_ticketMouseClicked

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        try {
            //String fl_id = tf_flightcode.getText();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select fl_date,fl_takeoff,fl_landing from flights  where fl_id = '" + tf_flightcode.getText() + "';");
            ResultSet rs = stmt.executeQuery();
            String date="" ,fl_takeoff="" ,fl_landing="";
            while(rs.next())
            {
                 date =rs.getString(1);
                 fl_takeoff =rs.getString(2);
                fl_landing=rs.getString(3);
            }
            
            if(!date.isEmpty()&&!fl_takeoff.isEmpty()&&!fl_landing.isEmpty())
            {
            tf_date.setText(date);
            tf_takeoff.setText(fl_takeoff);
            tf_landing.setText(fl_landing);
           
            }else{
                     JOptionPane.showMessageDialog(this, "Not Found"); //if the id not in the table 
            }
 
 
             
        } catch (SQLException ex) {
            System.out.println(ex); 
        }
    }//GEN-LAST:event_search2ActionPerformed

    private void tf_flightcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_flightcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_flightcodeActionPerformed

    private void tf_passportNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passportNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passportNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tickets_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tickets_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tickets_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tickets_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tickets_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_book1;
    private javax.swing.JButton btn_book2;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search2;
    private javax.swing.JTable t_ticket;
    private javax.swing.JTextField tf_Fname;
    private javax.swing.JTextField tf_Lname;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_flightcode;
    private javax.swing.JTextField tf_gender;
    private javax.swing.JTextField tf_landing;
    private javax.swing.JTextField tf_nationality;
    private javax.swing.JTextField tf_passportNumber;
    private javax.swing.JTextField tf_takeoff;
    // End of variables declaration//GEN-END:variables
}
